### ISSUE TITLE
Is this gem still being maintained? 

### ISSUE THREAD

**Issue by jkeen** [avantoss/timecop-rspec#1]
This gem looks great and I'd like to use it in my project but I'm hesitant since it hasn't been touched in in 3 years and doesn't seem to be on rubygems.org

I saw in a diff that it used to be part of a closed-source thing -- maybe updates got made to that branch of the project and not the OSS one? What's the deal with it?

**Comment by tmertens** [comment]
@jkeen The gem hasn't been touched in 3 years largely because it hasn't needed to. It just works.  You are right though - ideally it should get published to rubygems.

I'm using it in a project and it works great (rspec 3.9.0)
